---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/piragenth/heimdall/:/config
    ports:
      - 8080:80
    restart: unless-stopped
