version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8081:8080

#  db:
#    image: mysql:latest
#    container_name: mysql
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: <mysql_password>
#      MYSQL_DATABASE: python
