version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    volumes:
      - /home/piragenth/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      -  8123:8123 
    privileged: true
    network_mode: host
