---
version: "2.1"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-GjQAvZdqv--fUiTh_Bqm
      - ADVERTISE_IP=https://192.168.1.2:32400
    volumes:
      - /home/piragenth/config/plex/:/config/
      - /home/piragenth/drive-1/:/home/piragenth/drive-1/
      - /home/piragenth/drive-2/:/home/piragenth/drive-2/
    ports: 
      - 32400:32400
    restart: unless-stopped
