FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt update && echo 'nameserver 8.8.8.8' > /etc/resolv.conf && apt upgrade -y && apt install sudo nano git gdebi bmon nginx wget curl neofetch cmatrix -y 
