FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt update && echo 'nameserver 8.8.8.8' > /etc/resolv.conf && apt upgrade -y && apt install systemctl && apt install nala net-tools wget curl chromium-browser firefox openssh-client git novnc tightvncserver websockify sudo nano git gdebi bmon nginx wget curl neofetch cmatrix sddm kde-full -y 
ENV USER root
COPY Dockerfile-ubuntu.sh /Dockerfile-ubuntu.sh
RUN chmod a+x /Dockerfile-ubuntu.sh
RUN useradd -ms /bin/bash piragenth
RUN mkdir /.novnc
RUN apt-get -y install gedit vim
USER user

WORKDIR /.novnc
RUN wget -qO- https://github.com/novnc/noVNC/archive/v1.0.0.tar.gz | tar xz --strip 1 -C $PWD
RUN mkdir /.novnc/utils/websockify
RUN wget -qO- https://github.com/novnc/websockify/archive/v0.6.1.tar.gz | tar xz --strip 1 -C /.novnc/utils/websockify
RUN ln -s vnc.html index.html

CMD ["sh","/Dockerfile-ubuntu.sh"]