version: "3"

services:
  hugoapp:
    # we need extended, and nodejs for sass!
    image: klakegg/hugo:ext-nodejs
    container_name: ${SITE}
    command: server
    volumes: 
      - /home/piragenth/Documents/GitHub/ltfb:/src
    ports:
      - "1313:1313"

