version: '3'
services:
  hugo:
    container_name: hugo
    image: piragenthdocker/hugo:latest
    volumes:
      - "/home/piragenth/Documents/GitHub/linuxtutorialforbeginners:/srv/hugo"
    ports:
      - 8085:1313
    command: hugo server -s /srv/hugo --disableFastRender -w --bind 0.0.0.0
    restart: unless-stopped
