version: '3'
services:
  hugo:
    container_name: hugo
    image: ubuntu:latest
    volumes:
      - "/home/piragenth/Documents/GitHub/ltfb:/srv/hugo"
    ports:
      - 8081:1313
#    command: hugo server    
    restart: unless-stopped
