version: '3'
services:
  jekyll-serve:
    container_name: jekyll
    image: jekyll/jekyll:latest
    volumes:
      - "/home/piragenth/Documents/GitHub/piragenth-ltfb.github.io:/srv/jekyll"
    ports:
      - 80:4000
    command: 'jekyll serve'
    restart: unless-stopped
