version: '3.1'

services:
  joomla:
    container_name: joomla
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: <mysql_password>

  joomladb:
    container_name: jommla-db
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <mysql_password>
