version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /DATA/AppData/qbittorrent-linuxserver/config :/config
      - /DATA/AppData/qbittorrent-linuxserver/downloads:/downloads
    ports:
      - 8180:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
