---
version: "2.1"
services:
  remmina:
    image: linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /DATA/AppData/remmina/:/config
    ports:
      - 3010:3000
      - 3011:3001
    restart: unless-stopped
