version: "2"
services:
    ytdl_material:
        environment: 
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - /DATA/AppData/youtube-dl/appdata:/app/appdata
            - /home/piragenth/drive-2/Music/youtube/:/app/audio
            - /home/piragenth/drive-1/Videos/youtube/:/app/video
            - /DATA/AppData/youtube-dl/subscriptions:/app/subscriptions
            - /DATA/AppData/youtube-dl/users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
    ytdl-mongo-db:
        # If you are using a Raspberry Pi, use mongo:4.4.18
        image: mongo:4
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - /DATA/AppData/youtube-dl/db/:/data/db
