INSTALL_WEB_INTERFACE=true
WEBPASSWORD=b88676761a518dbf77bef2456cb6397a73b9e5d3a61c763e50ed4a0f16c541f1
PIHOLE_DNS_1=8.8.8.8
PIHOLE_DNS_2=8.8.4.4
PIHOLE_INTERFACE=eth0
QUERY_LOGGING=true
BLOCKING_ENABLED=true
